backend/modules/inventory/models/Item.php
<?php

namespace backend\modules\inventory\models;

use cornernote\linkall\LinkAllBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "item".
 *
 * @property integer $id
 * @property string $name
 * @property integer $vendor_id
 * @property integer $type_id
 * @property string $serial_number
 * @property string $price
 * @property string $weight
 * @property string $color
 * @property string $release_date
 * @property string $photo
 * @property string $created_date
 *
 * @property Type $type
 * @property Vendor $vendor
 */
class Item extends \yii\db\ActiveRecord
{

    public $tag_ids;

    /**
     * @var UploadedFile
     */
    public $imageFile;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_date',
                'updatedAtAttribute' => false,
                'value' => new Expression('NOW()'),
            ],
            LinkAllBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'vendor_id', 'type_id', 'serial_number', 'price', 'weight', 'color', 'release_date', 'photo'], 'required'],
            [['vendor_id', 'type_id'], 'integer'],
            [['price'], 'number', 'numberPattern' => '/^\d{1,8}(.\d{1,2})?$/', 'message' => 'Price is not valid' ],
            [['weight'], 'number', 'numberPattern' => '/^\d{1,7}(.\d{1,3})?$/', 'message' => 'Weight is not valid'],
            [['imageFile'], 'file'],
            [['release_date', 'created_date', 'tag_ids'], 'safe'],
            [['name', 'serial_number', 'color', 'photo'], 'string', 'max' => 50],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => Type::className(), 'targetAttribute' => ['type_id' => 'id']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Vendor::className(), 'targetAttribute' => ['vendor_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'vendor_id' => 'Vendor',
            'type_id' => 'Type',
            'serial_number' => 'Serial Number',
            'price' => 'Price',
            'weight' => 'Weight',
            'color' => 'Color',
            'release_date' => 'Release Date',
            'photo' => 'Photo',
            'created_date' => 'Created Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(Type::className(), ['id' => 'type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(Vendor::className(), ['id' => 'vendor_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function afterSave($insert, $changedAttributes)
    {
        $tags = [];
        foreach ($this->tag_ids as $tag_name) {
            $tag = Tag::getTagByName($tag_name);
            if ($tag) {
                $tags[] = $tag;
            }
        }
        $this->linkAll('tags', $tags);
        parent::afterSave($insert, $changedAttributes);
    }

    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('item_tag', ['item_id' => 'id']);
    }
}

backend/modules/inventory/controllers/ItemController.php
<?php

namespace backend\modules\inventory\controllers;

use Yii;
use backend\modules\inventory\models\Item;
use backend\modules\inventory\models\ItemSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;

/**
 * ItemController implements the CRUD actions for Item model.
 */
class ItemController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Item models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ItemSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Item model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (\Yii::$app->user->can('viewItem')) {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException('You are not allowed to view items');
        }
    }

    public function actionValidation(){
        $model = new Item();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())){
            Yii::$app->response->format = 'json';
            return ActiveForm::validate($model);
        }
        return null;
    }

    /**
     * Creates a new Item model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (\Yii::$app->user->can('createItem')) {

            $model = new Item();

            if ($model->load(Yii::$app->request->post())) {

                if ($model->imageFile !== null) {
                    $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                    $fileName = 'photos/' . uniqid(rand(), true) . "." . $model->imageFile->extension;
                    $model->imageFile->saveAs($fileName);
                    $model->photo = $fileName;
                }

                $model->created_date = time();
                $model->save();

                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Item has been updated.'));

                return $this->redirect(['view', 'id' => $model->id]);
            } else if (!\Yii::$app->request->isPost) {
                $model->load(Yii::$app->request->get());
                $model->tag_ids = ArrayHelper::map($model->tags, 'name', 'name');
            }

            return $this->render('create', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException('You are not allowed to create items');
        }

    }

    /**
     * Updates an existing Item model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (\Yii::$app->user->can('updateItem')) {

            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post())) {


                if($model->imageFile !== null) {
                    $model->imageFile = UploadedFile::getInstance($model, 'imageFile');

                    if (!empty($model->imageFile)) {
                        $fileName = 'photos/' . uniqid(rand(), true) . "." . $model->imageFile->extension;
                        $model->imageFile->saveAs($fileName);
                        $model->photo = $fileName;
                    }
                }

                $model->save();

                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Item has been updated.'));

                return $this->redirect(['view', 'id' => $model->id]);
            } else if (!\Yii::$app->request->isPost) {
                $model->load(Yii::$app->request->get());
                $model->tag_ids = ArrayHelper::map($model->tags, 'name', 'name');
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException('You are not allowed to update items');
        }
    }

    /**
     * Deletes an existing Item model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (\Yii::$app->user->can('updateItem')) {
            $model = $this->findModel($id);

            unlink($model->photo);

            $model->delete();

            return $this->redirect(['index']);
        } else {
            throw new \yii\web\ForbiddenHttpException('You are not allowed to delete items');
        }
    }

    /**
     * Finds the Item model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Item the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Item::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/modules/inventory/views/item/_form.php
<?php

use backend\modules\inventory\models\Tag;
use dosamigos\datepicker\DatePicker;
use kartik\color\ColorInput;
use kartik\file\FileInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use backend\modules\inventory\models\Vendor;
use backend\modules\inventory\models\Type;

/* @var $this yii\web\View */
/* @var $model backend\modules\inventory\models\Item */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-form">

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
        'enableAjaxValidation' => true,
        'validationUrl' => Url::toRoute('item/validation')
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>


    <?= $form->field($model, 'vendor_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Vendor::find()->orderBy(['name' => SORT_ASC])->all(), 'id', 'name'),
        'language' => 'en',
        'options' => ['placeholder' => 'Select Vendor'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'type_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Type::find()->orderBy(['name' => SORT_ASC])->all(), 'id', 'name'),
        'language' => 'en',
        'options' => ['placeholder' => 'Select Type'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>

    <?= $form->field($model, 'serial_number')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true])->hint('ex.: 149.99') ?>

    <?= $form->field($model, 'weight')->textInput(['maxlength' => true])->hint('ex.: 0.128') ?>

    <?= $form->field($model, 'color')->widget(ColorInput::classname(), [
        'showDefaultPalette' => false,
        'useNative' => false,
        'options' => [
            'placeholder' => 'Select Color',
            'readonly' => true
        ],
        'pluginOptions' => [
            'showInput' => false,
            'showInitial' => false,
            'showPalette' => true,
            'showPaletteOnly' => true,
            'showSelectionPalette' => true,
            'showAlpha' => false,
            'allowEmpty' => false,
            'preferredFormat' => 'name',
            'palette' => [
                [
                    "White", "Black", "Grey", "Silver", "Gold", "Brown",
                ],
                [
                    "Red", "Orange", "Yellow", "Indigo", "Maroon", "Pink"
                ],
                [
                    "Blue", "Green", "Violet", "Cyan", "Magenta", "Purple",
                ],
            ]
        ]
    ]); ?>



    <?= $form->field($model, 'release_date')->widget(
        DatePicker::className(), [
        // inline too, not bad
        'inline' => false,
        // modify template for custom rendering
        //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'yyyy-mm-dd'
        ]
    ]);?>

    <?= $form->field($model, 'imageFile')->widget(FileInput::classname(), [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'initialPreview'=>[!$model->isNewRecord ? $model->photo : ''],
            'initialPreviewAsData'=>true,
            'overwriteInitial'=>true,

            'showCaption' => false,
            'showRemove' => false,
            'showUpload' => false,
            'browseClass' => 'btn btn-primary btn-block',
            'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
            'browseLabel' =>  'Select Photo'
        ],
    ]);
    ?>

    <fieldset>
        <legend>Tags</legend>
        <?= $form->field($model, 'tag_ids')->widget(Select2::className(), [
            'model' => $model,
            'attribute' => 'tag_ids',
            'data' => ArrayHelper::map(Tag::find()->all(), 'name', 'name'),
            'options' => [
                'multiple' => true,
            ],
            'pluginOptions' => [
                'tags' => true,
            ],
        ]); ?>
    </fieldset>



    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/inventory/views/item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\inventory\models\ItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-search">

    <?php $form = ActiveForm::begin([
        'id' => 'item-search',
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'globalSearch') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Reset', ['index'], ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/inventory/views/item/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\inventory\models\Item */

$this->title = 'Create Item';
$this->params['breadcrumbs'][] = ['label' => 'Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/inventory/views/item/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\modules\inventory\models\ItemSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Items';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Item', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'name',
            'color',
            [
                'attribute' => 'vendor_id',
                'value' => 'vendor.name'
            ],
            [
                'attribute' => 'type_id',
                'value' => 'type.name'
            ],
            'price',
            'release_date',


            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/modules/inventory/views/item/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\inventory\models\Item */

$this->title = 'Update Item: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="item-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/inventory/views/item/view.php
<?php

use backend\modules\inventory\models\Tag;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\DetailView;
use backend\modules\inventory\models\ItemTag;

/* @var $this yii\web\View */
/* @var $model backend\modules\inventory\models\Item */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Items', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            [
                'attribute' => 'vendor_id',
                'value'=> $model->vendor->name
            ],
            [
                'attribute' => 'type_id',
                'value'=> $model->type->name
            ],
            'serial_number',
            'price',
            'weight',
            'color',
            'release_date',
            [
                'attribute'=>'photo',
                'value'=>$model->photo,
                'format' => ['image',['height'=>'250']],
            ],
            'created_date',
            [
                'attribute' => 'tags',
                'value' => call_user_func(function ($data) {

                    $tag_query="SELECT (SELECT name FROM tag WHERE id = tag_id) as 'tag' FROM item_tag WHERE item_id =".$data->id;

                    $resultString = "";

                    foreach(Yii::$app->db->createCommand($tag_query)->queryAll() as $tag){
                        $resultString = $resultString.$tag['tag'].', ';
                    }
                    return $resultString;
                }, $model),
            ]
        ],
    ]) ?>


</div>